export const CHAT_PUSH_MESSAGES = 'CHAT_PUSH_MESSAGES'
export const CHAT_SET_MATCH = 'CHAT_SET_MATCH'
export const CHAT_SEND_MESSAGE = 'CHAT_SEND_MESSAGE'
export const CHAT_SET_MESSAGES = 'CHAT_SET_MESSAGES'
export const CHAT_UPDATE_DRAFT = 'CHAT_UPDATE_DRAFT'

export const CREATION_NEXT_STEP = 'CREATION_NEXT_STEP'
export const CREATION_PREVIOUS_STEP = 'CREATION_PREVIOUS_STEP'
export const CREATION_UPDATE_FIELD = 'CREATION_UPDATE_FIELD'
export const CREATION_SET_ERROR = 'CREATION_SET_ERROR'
export const CREATION_RESET_ERRORS = 'CREATION_RESET_ERRORS'

export const MATCHES_SET_MATCHES = 'MATCHES_SET_MATCHES'

export const ONBOARDING_NEXT_STEP = 'ONBOARDING_NEXT_STEP'
export const ONBOARDING_PREVIOUS_STEP = 'ONBOARDING_PREVIOUS_STEP'

export const SETTINGS_UPDATE_FIELD = 'SETTINGS_UPDATE_FIELD'

export const SIGN_DISPLAY_SIGNIN = 'SIGN_DISPLAY_SIGNIN'
export const SIGN_DISPLAY_SIGNUP = 'SIGN_DISPLAY_SIGNUP'
export const SIGN_UPDATE_FIELD = 'SIGN_UPDATE_FIELD'
export const SIGN_RESET_ERRORS = 'SIGN_RESET_ERRORS'
export const SIGN_SET_ERROR = 'SIGN_SET_ERROR'

export const SUGGESTIONS_ADD_SUGGESTIONS = 'SUGGESTIONS_ADD_SUGGESTIONS'
export const SUGGESTIONS_REMOVE_SUGGESTION = 'SUGGESTIONS_REMOVE_SUGGESTION'

export const USER_DISPLAY_USER = 'USER_DISPLAY_USER'

export const UX_DISPLAY_MATCH_MODAL = 'UX_DISPLAY_MATCH_MODAL'
export const UX_HIDE_MATCH_MODAL = 'UX_HIDE_MATCH_MODAL'
